#!/usr/bin/env node
// Builds tools/music.js into c64/src/musicdata.s for the player in music.s.
//
// A pattern byte: steps code (bits 7-6: 1, 2, 4, 8 steps) | note (bits 5-0:
// 0 rest, 1-60 semitones up from A1, 62 hold the note before). $FF ends it.
// An order byte: 0-$7F a pattern, $80-$BF transpose (-32..+31), $FF loop.
// A tune: tempo, then for each voice: wave, AD, SR, pw, order (word).
// The tables and most tunes ride under the I/O chips; a tune marked low (and
// the patterns only it uses) goes in main memory, which the player reads the
// same way.
'use strict';
const fs = require('fs');
const path = require('path');
const { patterns, songs } = require('./music.js');

const NAMES = { C: 0, 'C#': 1, D: 2, 'D#': 3, E: 4, F: 5, 'F#': 6, G: 7, 'G#': 8, A: 9, 'A#': 10, B: 11 };
const STEPS = { 1: 0, 2: 1, 4: 2, 8: 3 };
function noteIndex(tok) {
  const m = /^([A-G]#?)(\d)$/.exec(tok);
  if (!m) throw new Error('bad note ' + tok);
  const n = (+m[2]) * 12 + NAMES[m[1]] - (1 * 12 + 9) + 1;   // A1 = 1
  if (n < 1 || n > 60) throw new Error('note out of range ' + tok);
  return n;
}
function packPattern(name, src) {
  let bytes = [], total = 0;
  for (const ev of src.trim().split(/\s+/)) {
    const [tok, st] = ev.split('/');
    if (!(st in STEPS)) throw new Error(`pattern ${name}: steps ${st}`);
    total += +st;
    const n = tok === 'r' ? 0 : tok === '-' ? 62 : noteIndex(tok);
    bytes.push(STEPS[st] << 6 | n);
  }
  if (total % 16) console.warn(`pattern ${name}: ${total} steps (not whole bars)`);
  return [...bytes, 0xFF];
}

// only the patterns the tunes use, in order; which of them only low tunes use
const used = [], high = new Set();
const orders = songs.map(s => s.voices.map(v => {
  const out = [0x80 + 32];                   // transpose 0 at the top of each loop
  for (const tok of v.order.trim().split(/\s+/)) {
    if (/^[+-]\d+$/.test(tok)) { const t = +tok; if (t < -32 || t > 31) throw new Error('transpose ' + tok); out.push(0x80 + 32 + t); continue; }
    if (!(tok in patterns)) throw new Error(`${s.name}: no pattern ${tok}`);
    if (!used.includes(tok)) used.push(tok);
    if (!s.low) high.add(tok);
    out.push(used.indexOf(tok));
  }
  return [...out, 0xFF];
}));

// PAL: SID frequency = Hz * 2^24 / 985248 -- for the top octave only (notes
// 49-60, A5 up); the player halves it for each octave down
const freq = [];
for (let n = 49; n <= 60; n++) freq.push(Math.round(55 * Math.pow(2, (n - 1) / 12) * 16777216 / 985248));

const bytes = l => '        .byte ' + l.map(b => '$' + b.toString(16).padStart(2, '0')).join(', ');
let s = '; Generated by tools/gen_music.js from tools/music.js -- do not edit.\n';
s += `        .export mus_freq_lo, mus_freq_hi, mus_pat_lo, mus_pat_hi, mus_songs\n\nNSONGS = ${songs.length}\n\n`;
// (in the art segment: copied under the I/O chips at startup with the
// battle portraits; the player banks I/O out to read it)
s += '        .segment "HISPR"\n';
s += 'mus_freq_lo:\n' + bytes(freq.map(f => f & 0xFF)) + '\n';
s += 'mus_freq_hi:\n' + bytes(freq.map(f => f >> 8)) + '\n';
s += 'mus_pat_lo:\n        .lobytes ' + used.map(p => 'pat_' + p).join(', ') + '\n';
s += 'mus_pat_hi:\n        .hibytes ' + used.map(p => 'pat_' + p).join(', ') + '\n';
s += 'mus_songs:\n        .word ' + songs.map(x => 'song_' + x.name).join(', ') + '\n';
let total = 12 * 2 + used.length * 2 + songs.length * 2, low = 0;
for (const lowPart of [false, true]) {
  if (lowPart) s += '\n; (main memory)\n        .segment "RODATA"\n';
  let n = 0;
  songs.forEach((x, i) => {
    if (!!x.low !== lowPart) return;
    s += `song_${x.name}:\n        .byte ${x.tempo}\n`;
    x.voices.forEach((v, k) => { s += bytes([v.wave, v.ad, v.sr, v.pw]) + `\n        .word ord_${x.name}_${k}\n`; });
    x.voices.forEach((v, k) => { s += `ord_${x.name}_${k}:\n` + bytes(orders[i][k]) + '\n'; n += orders[i][k].length; });
    n += 11;
  });
  used.forEach(p => {
    if (high.has(p) === lowPart) return;
    const b = packPattern(p, patterns[p]); n += b.length; s += `pat_${p}:\n` + bytes(b) + '\n';
  });
  total += n; if (lowPart) low = n;
}
fs.writeFileSync(path.resolve(__dirname, '..', 'src', 'musicdata.s'), s);
console.log(`music: ${songs.length} tunes, ${used.length} patterns, ${total} bytes (${low} in main memory)`);
