#!/usr/bin/env node
// Converts the class Power Trees and perks in js/data.js into c64/src/tree.c.
// Effect values become integers: fractions are stored as percent (0.35 -> 35),
// flat bonuses (HP, defence, regen...) are kept as-is.
'use strict';
const fs = require('fs');
const path = require('path');

const ROOT = path.resolve(__dirname, '..', '..');
const OUT = path.resolve(__dirname, '..', 'src');
const src = fs.readFileSync(path.join(ROOT, 'js', 'data.js'), 'utf8');
const { CLASSES } = new Function(src + ';return { CLASSES };')();

// effect key -> [C enum, is a fraction (stored as percent)]
const EFFECTS = {
  spellDmg: ['E_SPELLDMG', true], basicDmg: ['E_BASICDMG', true], crit: ['E_CRIT', true],
  polishZone: ['E_POLISH', true], charges: ['E_CHARGES', false], chargeSave: ['E_CHARGESAVE', true],
  reviveFrac: ['E_REVIVE', true], mineYield: ['E_MINEYIELD', false], xpGain: ['E_XPGAIN', true],
  rareLuck: ['E_RARELUCK', true], hpMax: ['E_HPMAX', false], defFlat: ['E_DEFFLAT', false],
  shieldPower: ['E_SHIELD', true], healOnWin: ['E_HEALONWIN', true], lastStand: ['E_LASTSTAND', false],
  regen: ['E_REGEN', false], unicornPower: ['E_UNICORN', true], summonTurns: ['E_SUMMONTURNS', false],
  healPower: ['E_HEALPOWER', true], fleeSure: ['E_FLEESURE', false],
  // only on gear (js/loot.js), never in a tree
  atkFlat: ['E_ATKFLAT', false], magFlat: ['E_MAGFLAT', false], dodge: ['E_DODGE', true],
};
const ORDER = ['mage', 'knight', 'whisperer'];

function effs(obj, where) {
  const list = Object.entries(obj).map(([k, v]) => {
    if (!EFFECTS[k]) throw new Error(`unknown effect ${k} in ${where}`);
    const [name, frac] = EFFECTS[k];
    return [name, frac ? Math.round(v * 100) : v];
  });
  if (list.length > 2) throw new Error(`more than 2 effects in ${where}`);
  while (list.length < 2) list.push(['E_NONE', 0]);
  return list;
}
const q = s => JSON.stringify(s.replace(/[’‘]/g, "'").replace(/[—–]/g, '-'));

let h = '/* Generated by tools/gen_data.js from js/data.js -- do not edit. */\n#ifndef TREE_H\n#define TREE_H\n\n';
h += 'enum { E_NONE, ' + Object.values(EFFECTS).map(e => e[0]).join(', ') + ', E_COUNT };\n\n';
h += 'typedef struct { unsigned char key; signed char val; } Eff;\n';
h += 'typedef struct { Eff eff[2]; } SkillNode;\n';
h += 'typedef struct { unsigned char color; SkillNode node[5]; } Branch;\n\n';
h += 'extern const Branch tree[3][3];      /* [class][branch]: effects, resident */\n';
h += '/* names and descriptions: tree_text.h, used only by the Power Tree overlays */\n';
h += 'extern const Eff class_perk[3][2];\n\n#endif\n';

// branch colour -> nearest of the 8 hi-res text colours
const TXT = [[0, 0, 0], [255, 255, 255], [129, 51, 56], [117, 206, 200], [142, 60, 151], [86, 172, 77], [46, 44, 155], [237, 241, 113]];
function txtColor(hex) {
  const c = [1, 3, 5].map(i => parseInt(hex.slice(i, i + 2), 16));
  let best = 1, bd = Infinity;
  for (let i = 1; i < 8; i++) {
    const d = TXT[i].reduce((a, v, j) => a + (v - c[j]) ** 2, 0);
    if (d < bd) { bd = d; best = i; }
  }
  return best;
}

let c = '/* Generated by tools/gen_data.js from js/data.js -- do not edit. */\n#include "tree.h"\n\n';
c += 'const Branch tree[3][3] = {\n';
for (const cid of ORDER) {
  c += `  { /* ${cid} */\n`;
  for (const br of CLASSES[cid].tree) {
    c += `    { ${txtColor(br.color)}, {\n`;
    for (const n of br.nodes) {
      const e = effs(n.eff, n.id);
      c += `      { { { ${e[0][0]}, ${e[0][1]} }, { ${e[1][0]}, ${e[1][1]} } } }, /* ${n.name} */\n`;
    }
    c += '    } },\n';
  }
  c += '  },\n';
}
c += '};\n\nconst Eff class_perk[3][2] = {\n';
for (const cid of ORDER) {
  const e = effs(CLASSES[cid].perk, cid + ' perk');
  c += `  { { ${e[0][0]}, ${e[0][1]} }, { ${e[1][0]}, ${e[1][1]} } }, /* ${cid} */\n`;
}
c += '};\n';

// Power Tree text for one class, picked by TREE_CLASS: each class's tree
// screen is its own overlay (ov_tree_*.c) and carries only its own text.
let t = '/* Generated by tools/gen_data.js from js/data.js -- do not edit.\n * Power Tree text; include with TREE_CLASS set (see ov_tree.inc). */\n';
ORDER.forEach((cid, i) => {
  const tr = CLASSES[cid].tree;
  t += `${i ? '#elif' : '#if'} TREE_CLASS == ${i} /* ${cid} */\n`;
  t += 'static const char *const branch_name[3] = { ' + tr.map(br => q(br.branch)).join(', ') + ' };\n';
  t += 'static const char *const skill_name[3][5] = {\n' + tr.map(br => '  { ' + br.nodes.map(n => q(n.name)).join(', ') + ' }').join(',\n') + '\n};\n';
  t += 'static const char *const skill_desc[3][5] = {\n' + tr.map(br => '  { ' + br.nodes.map(n => q(n.desc)).join(',\n    ') + ' }').join(',\n') + '\n};\n';
});
t += '#endif\n';
fs.writeFileSync(path.join(OUT, 'tree_text.h'), t);
fs.writeFileSync(path.join(OUT, 'tree.h'), h);
fs.writeFileSync(path.join(OUT, 'tree.c'), c);
console.log('tree: 3 classes x 3 branches x 5 skills');
