/* Generated by tools/gen_assets.js from js/sprites.js -- do not edit. */
#ifndef ASSETS_H
#define ASSETS_H

#define TILE_BASE 96
#define MC1_COLOR 0
#define MC2_COLOR 9

#define T_GRASS 0
#define T_GRASS2 1
#define T_FLOWER 2
#define T_TREE 3
#define T_WATER 4
#define T_COTTAGE 5
#define T_WALL 6
#define T_HOUSE 7
#define T_KITCHEN 8
#define T_FACTORY 9
#define T_STALLS 10
#define T_TRAINING 11
#define T_PLOT 12
#define T_ROCK 13
#define T_SIGN 14
#define T_HOMESIGN 15
#define T_CLOUDGATE 16
#define T_BOARD 17
#define T_FORGE 18
#define T_NODE 19
#define T_GLINT 20
#define T_DUNGEON 21
#define T_PATH 22
#define T_M_SLIME 23
#define T_M_BAT 24
#define T_M_SHROOM 25
#define T_M_FOX 26
#define T_M_GOLEM 27
#define T_M_GAZER 28
#define T_M_SPAWNLING 29
#define T_M_BOGMAW 30
#define T_M_VOLTRA 31
#define T_M_MILDEW 32
#define T_M_UMBRELLA 33
#define T_N_MAYOR 34
#define T_N_GRANDMA 35
#define T_N_FOREMAN 36
#define T_N_PIP 37
#define T_N_BAKER 38
#define T_N_WILLOW 39
#define T_COUNT 40

#define CH_HEART 90
#define CH_GEM 91
#define CH_SOLID 92
#define CH_BAR 93
#define CH_STAR 94
#define CH_POINTER 95

#define CHARSET_BYTES 2048
extern const unsigned char charset[CHARSET_BYTES];
extern const unsigned char tile_color[T_COUNT][4];
#define PLAYER_SPRITES 3
#define BATTLE_SPRITES 20
/* heroes: outline, detail (hi-res), fill (multicolour; $D025/$D026 = hero_mc) */
extern const unsigned char hero_spr[PLAYER_SPRITES][3][63];
extern const unsigned char hero_col[PLAYER_SPRITES][3];
extern const unsigned char hero_mc[PLAYER_SPRITES][2];
/* battle portraits: hi-res layers, left halves, packed (under the I/O chips): mon_sprites() */
extern const unsigned char mon_art[];
#define KEEPER_SPRITE0 11   /* from here on, the art is foe_art[] (the big foes' overlay) */
#define CASTLE_SPRITE0 14   /* (the castle's) */
extern const unsigned char foe_art[];
extern const unsigned int mon_off[BATTLE_SPRITES];
extern const unsigned char mon_nl[BATTLE_SPRITES];
extern const unsigned char mon_col[BATTLE_SPRITES][4];

#endif
