/* Generated by tools/gen_assets.js from js/sprites.js -- do not edit. */
#ifndef ASSETS_H
#define ASSETS_H

#define TILE_BASE 96
#define MC1_COLOR 0
#define MC2_COLOR 9

#define T_GRASS 0
#define T_GRASS2 1
#define T_FLOWER 2
#define T_TREE 3
#define T_WATER 4
#define T_COTTAGE 5
#define T_WALL 6
#define T_HOUSE 7
#define T_SIGN 8
#define T_HOMESIGN 9
#define T_CLOUDGATE 10
#define T_BOARD 11
#define T_FORGE 12
#define T_NODE 13
#define T_GLINT 14
#define T_DUNGEON 15
#define T_PATH 16
#define T_M_SLIME 17
#define T_M_BAT 18
#define T_M_SHROOM 19
#define T_M_FOX 20
#define T_M_GOLEM 21
#define T_M_GAZER 22
#define T_M_SPAWNLING 23
#define T_M_BOGMAW 24
#define T_M_VOLTRA 25
#define T_M_MILDEW 26
#define T_M_UMBRELLA 27
#define T_N_MAYOR 28
#define T_N_GRANDMA 29
#define T_N_FOREMAN 30
#define T_N_PIP 31
#define T_N_BAKER 32
#define T_N_WILLOW 33
#define T_COUNT 34

#define CH_HEART 90
#define CH_GEM 91
#define CH_SOLID 92
#define CH_BAR 93
#define CH_STAR 94
#define CH_POINTER 95

#define CHARSET_BYTES 1856
extern const unsigned char charset[CHARSET_BYTES];
extern const unsigned char tile_color[T_COUNT][4];
#define PLAYER_SPRITES 3
#define BATTLE_SPRITES 11
extern const unsigned char player_spr[PLAYER_SPRITES][3][32];
extern const unsigned char player_spr_col[PLAYER_SPRITES][3];
extern const unsigned char battle_spr[BATTLE_SPRITES][3][32];
extern const unsigned char battle_spr_col[BATTLE_SPRITES][3];

#endif
