; Generated by tools/gen_music.js from tools/music.js -- do not edit.
        .export mus_freq_lo, mus_freq_hi, mus_pat_lo, mus_pat_hi, mus_songs

NSONGS = 4

        .segment "HISPR"
mus_freq_lo:
        .byte $89, $04, $b4, $9c, $c0, $23, $c8, $b4, $eb, $72, $4c, $80
mus_freq_hi:
        .byte $3a, $3e, $41, $45, $49, $4e, $52, $57, $5c, $62, $68, $6e
mus_pat_lo:
        .lobytes pat_t1, pat_t2, pat_t3, pat_t4, pat_t5, pat_t6, pat_t7, pat_t8, pat_bassR5, pat_v1, pat_v2, pat_v3, pat_v4, pat_v6, pat_v7, pat_v8, pat_bassPump, pat_w1, pat_w2, pat_w3, pat_w4, pat_w5, pat_w6, pat_w7, pat_w8, pat_bassDrone, pat_b1, pat_b2, pat_b3, pat_b4, pat_b5, pat_b6, pat_b7, pat_b8, pat_bassRun
mus_pat_hi:
        .hibytes pat_t1, pat_t2, pat_t3, pat_t4, pat_t5, pat_t6, pat_t7, pat_t8, pat_bassR5, pat_v1, pat_v2, pat_v3, pat_v4, pat_v6, pat_v7, pat_v8, pat_bassPump, pat_w1, pat_w2, pat_w3, pat_w4, pat_w5, pat_w6, pat_w7, pat_w8, pat_bassDrone, pat_b1, pat_b2, pat_b3, pat_b4, pat_b5, pat_b6, pat_b7, pat_b8, pat_bassRun
mus_songs:
        .word song_title, song_village, song_wilds, song_battle
song_title:
        .byte 7
        .byte $40, $08, $a9, $08
        .word ord_title_0
        .byte $10, $08, $88, $00
        .word ord_title_1
song_village:
        .byte 5
        .byte $40, $06, $89, $06
        .word ord_village_0
        .byte $10, $06, $00, $00
        .word ord_village_1
song_wilds:
        .byte 8
        .byte $40, $2a, $9a, $04
        .word ord_wilds_0
        .byte $10, $4a, $aa, $00
        .word ord_wilds_1
song_battle:
        .byte 4
        .byte $40, $05, $89, $0a
        .word ord_battle_0
        .byte $20, $05, $00, $00
        .word ord_battle_1
ord_title_0:
        .byte $a0, $00, $01, $02, $03, $04, $05, $06, $07, $ff
ord_title_1:
        .byte $a0, $08, $9c, $08, $a3, $08, $9e, $08, $a0, $08, $9c, $08, $a3, $08, $9e, $08, $ff
ord_village_0:
        .byte $a0, $09, $0a, $0b, $0c, $09, $0d, $0e, $0f, $ff
ord_village_1:
        .byte $a0, $10, $9d, $10, $99, $10, $9b, $10, $a0, $10, $9d, $10, $99, $10, $9b, $10, $ff
ord_wilds_0:
        .byte $a0, $11, $12, $13, $14, $15, $16, $17, $18, $ff
ord_wilds_1:
        .byte $a0, $19, $9c, $19, $a5, $19, $a7, $19, $a0, $19, $9c, $19, $a5, $19, $a7, $19, $ff
ord_battle_0:
        .byte $a0, $1a, $1b, $1c, $1d, $1e, $1f, $20, $21, $ff
ord_battle_1:
        .byte $a0, $22, $9c, $22, $9e, $22, $9b, $22, $a0, $22, $9c, $22, $9e, $22, $9b, $22, $ff
pat_t1:
        .byte $ac, $6a, $68, $a7, $a8, $ff
pat_t2:
        .byte $e5, $be, $a8, $ff
pat_t3:
        .byte $a3, $ac, $6a, $68, $aa, $ff
pat_t4:
        .byte $e7, $fe, $ff
pat_t5:
        .byte $ac, $b1, $6f, $6c, $a8, $ff
pat_t6:
        .byte $ad, $6c, $6a, $e8, $ff
pat_t7:
        .byte $ac, $6a, $68, $a3, $a8, $ff
pat_t8:
        .byte $e7, $80, $63, $67, $ff
pat_bassR5:
        .byte $8d, $94, $99, $94, $ff
pat_v1:
        .byte $6c, $6f, $b4, $73, $71, $af, $ff
pat_v2:
        .byte $b1, $ac, $a8, $ac, $ff
pat_v3:
        .byte $6d, $6f, $b1, $6f, $6d, $ac, $ff
pat_v4:
        .byte $aa, $af, $a7, $aa, $ff
pat_v6:
        .byte $71, $73, $b4, $ec, $ff
pat_v7:
        .byte $6d, $6c, $aa, $68, $6a, $ac, $ff
pat_v8:
        .byte $aa, $a7, $e8, $ff
pat_bassPump:
        .byte $50, $40, $57, $40, $5c, $40, $57, $40, $ff
pat_w1:
        .byte $80, $a5, $aa, $ad, $ff
pat_w2:
        .byte $ec, $ea, $ff
pat_w3:
        .byte $80, $a3, $a6, $aa, $ff
pat_w4:
        .byte $e9, $e5, $ff
pat_w5:
        .byte $80, $ad, $ac, $aa, $ff
pat_w6:
        .byte $ed, $ea, $ff
pat_w7:
        .byte $a6, $a5, $a3, $a6, $ff
pat_w8:
        .byte $e5, $fe, $ff
pat_bassDrone:
        .byte $c6, $cd, $ff
pat_b1:
        .byte $6c, $40, $6c, $6f, $b3, $71, $6f, $ff
pat_b2:
        .byte $6c, $40, $6c, $6f, $b4, $73, $6f, $ff
pat_b3:
        .byte $6e, $40, $6e, $71, $b6, $74, $71, $ff
pat_b4:
        .byte $b3, $71, $6f, $ae, $ab, $ff
pat_b5:
        .byte $6c, $6f, $73, $78, $76, $73, $6f, $73, $ff
pat_b6:
        .byte $b4, $73, $71, $af, $ac, $ff
pat_b7:
        .byte $6e, $71, $76, $6e, $6c, $6a, $6e, $71, $ff
pat_b8:
        .byte $f3, $ab, $ae, $ff
pat_bassRun:
        .byte $48, $54, $48, $54, $48, $54, $48, $54, $ff
