/* Generated by tools/gen_data.js from js/data.js -- do not edit. */
#include "tree.h"

const Branch tree[3][3] = {
  { /* mage */
    { "Radiance", 4, {
      { "Focused Light", "+15% spell damage", { { E_SPELLDMG, 15 }, { E_NONE, 0 } } },
      { "Prismatic Edge", "+12% crit chance", { { E_CRIT, 12 }, { E_NONE, 0 } } },
      { "Supernova Heart", "+25% spell damage", { { E_SPELLDMG, 25 }, { E_NONE, 0 } } },
      { "Starfire", "+20% spell damage", { { E_SPELLDMG, 20 }, { E_NONE, 0 } } },
      { "Prismatic Nova", "CAPSTONE: +40% spell damage & +12% crit", { { E_SPELLDMG, 40 }, { E_CRIT, 12 } } },
    } },
    { "Flow", 3, {
      { "Steady Hands", "Big boost to polish quality odds", { { E_POLISH, 35 }, { E_NONE, 0 } } },
      { "Echo Casting", "+1 charge every time you craft a spell", { { E_CHARGES, 1 }, { E_NONE, 0 } } },
      { "Chain Light", "25% chance casting is free", { { E_CHARGESAVE, 25 }, { E_NONE, 0 } } },
      { "Mana Well", "+1 craft charge & 15% free casts", { { E_CHARGES, 1 }, { E_CHARGESAVE, 15 } } },
      { "Second Dawn", "CAPSTONE: once per life, cheat death and revive at 50% HP", { { E_REVIVE, 50 }, { E_NONE, 0 } } },
    } },
    { "Fortune", 7, {
      { "Gem Sense", "+1 mineral from every node", { { E_MINEYIELD, 1 }, { E_NONE, 0 } } },
      { "Scholar", "+25% XP from battles", { { E_XPGAIN, 25 }, { E_NONE, 0 } } },
      { "Rainbow Luck", "20% chance of a bonus rare gem when mining", { { E_RARELUCK, 20 }, { E_NONE, 0 } } },
      { "Gem Diviner", "+1 mineral & +12% rare gem luck", { { E_MINEYIELD, 1 }, { E_RARELUCK, 12 } } },
      { "Midas Prism", "CAPSTONE: +40% XP & +20% rare gem luck", { { E_XPGAIN, 40 }, { E_RARELUCK, 20 } } },
    } },
  },
  { /* knight */
    { "Bulwark", 3, {
      { "Stonewall", "+25 max HP", { { E_HPMAX, 25 }, { E_NONE, 0 } } },
      { "Crystal Plate", "+3 defense", { { E_DEFFLAT, 3 }, { E_NONE, 0 } } },
      { "Aegis of Facets", "Prism Shield blocks far more", { { E_SHIELD, 50 }, { E_NONE, 0 } } },
      { "Bastion", "+30 max HP & +2 defense", { { E_HPMAX, 30 }, { E_DEFFLAT, 2 } } },
      { "Undying", "CAPSTONE: once per life, revive at 50% HP", { { E_REVIVE, 50 }, { E_NONE, 0 } } },
    } },
    { "Shatter", 7, {
      { "Heavy Bonk", "+25% Bonk damage", { { E_BASICDMG, 25 }, { E_NONE, 0 } } },
      { "Fracture Point", "+12% crit chance", { { E_CRIT, 12 }, { E_NONE, 0 } } },
      { "Meteor Bonk", "+40% Bonk damage", { { E_BASICDMG, 40 }, { E_NONE, 0 } } },
      { "Devastate", "+30% Bonk damage & +6% crit", { { E_BASICDMG, 30 }, { E_CRIT, 6 } } },
      { "Cataclysm", "CAPSTONE: +50% Bonk damage & +12% crit", { { E_BASICDMG, 50 }, { E_CRIT, 12 } } },
    } },
    { "Resolve", 3, {
      { "Second Wind", "Heal 25% HP after every victory", { { E_HEALONWIN, 25 }, { E_NONE, 0 } } },
      { "Iron Will", "+2 defense", { { E_DEFFLAT, 2 }, { E_NONE, 0 } } },
      { "Last Stand", "Survive a fatal blow once per battle", { { E_LASTSTAND, 1 }, { E_NONE, 0 } } },
      { "Warden Spirit", "+3 regen & heal 15% after each win", { { E_REGEN, 3 }, { E_HEALONWIN, 15 } } },
      { "Immovable", "CAPSTONE: +25% max HP & +4 defense", { { E_HPMAX, 25 }, { E_DEFFLAT, 4 } } },
    } },
  },
  { /* whisperer */
    { "Kinship", 4, {
      { "Best Friends", "Unicorns 30% stronger", { { E_UNICORN, 30 }, { E_NONE, 0 } } },
      { "Loyal Companion", "Summons last 2 extra turns", { { E_SUMMONTURNS, 2 }, { E_NONE, 0 } } },
      { "Radiant Herd", "Unicorns 50% stronger", { { E_UNICORN, 50 }, { E_NONE, 0 } } },
      { "Herd Leader", "Summons last +3 turns", { { E_SUMMONTURNS, 3 }, { E_NONE, 0 } } },
      { "Celestial Herd", "CAPSTONE: +70% unicorn power", { { E_UNICORN, 70 }, { E_NONE, 0 } } },
    } },
    { "Blessing", 3, {
      { "Gentle Glow", "Healing 30% stronger", { { E_HEALPOWER, 30 }, { E_NONE, 0 } } },
      { "Warm Heart", "+20 max HP", { { E_HPMAX, 20 }, { E_NONE, 0 } } },
      { "Meadow Soul", "Regenerate 3 HP every battle turn", { { E_REGEN, 3 }, { E_NONE, 0 } } },
      { "Radiant Soul", "+25% healing & +15 max HP", { { E_HEALPOWER, 25 }, { E_HPMAX, 15 } } },
      { "Unicorn's Gift", "CAPSTONE: once per life, your unicorn sacrifices itself to revive you at 50% HP", { { E_REVIVE, 50 }, { E_NONE, 0 } } },
    } },
    { "Wild", 7, {
      { "Forager", "+1 mineral from every node", { { E_MINEYIELD, 1 }, { E_NONE, 0 } } },
      { "Fae Steps", "Fleeing always works, never ambushed", { { E_FLEESURE, 1 }, { E_NONE, 0 } } },
      { "Old Tales", "+25% XP from battles", { { E_XPGAIN, 25 }, { E_NONE, 0 } } },
      { "Lucky Charm", "+18% chance of a bonus rare gem when mining", { { E_RARELUCK, 18 }, { E_NONE, 0 } } },
      { "Storyteller", "CAPSTONE: +40% XP from battles", { { E_XPGAIN, 40 }, { E_NONE, 0 } } },
    } },
  },
};

const Eff class_perk[3][2] = {
  { { E_SPELLDMG, 35 }, { E_CHARGESAVE, 10 } }, /* mage */
  { { E_BASICDMG, 50 }, { E_SPELLDMG, -10 } }, /* knight */
  { { E_UNICORN, 35 }, { E_NONE, 0 } }, /* whisperer */
};
