/* Generated by tools/gen_data.js from js/data.js -- do not edit.
 * Power Tree text; include with TREE_CLASS set (see ov_tree.inc). */
#if TREE_CLASS == 0 /* mage */
static const char *const branch_name[3] = { "Radiance", "Flow", "Fortune" };
static const char *const skill_name[3][5] = {
  { "Focused Light", "Prismatic Edge", "Supernova Heart", "Starfire", "Prismatic Nova" },
  { "Steady Hands", "Echo Casting", "Chain Light", "Mana Well", "Second Dawn" },
  { "Gem Sense", "Scholar", "Rainbow Luck", "Gem Diviner", "Midas Prism" }
};
static const char *const skill_desc[3][5] = {
  { "+15% spell damage",
    "+12% crit chance",
    "+25% spell damage",
    "+20% spell damage",
    "CAPSTONE: +40% spell damage & +12% crit" },
  { "Big boost to polish quality odds",
    "+1 charge every time you craft a spell",
    "25% chance casting is free",
    "+1 craft charge & 15% free casts",
    "CAPSTONE: once per life, cheat death and revive at 50% HP" },
  { "+1 mineral from every node",
    "+25% XP from battles",
    "20% chance of a bonus rare gem when mining",
    "+1 mineral & +12% rare gem luck",
    "CAPSTONE: +40% XP & +20% rare gem luck" }
};
#elif TREE_CLASS == 1 /* knight */
static const char *const branch_name[3] = { "Bulwark", "Shatter", "Resolve" };
static const char *const skill_name[3][5] = {
  { "Stonewall", "Crystal Plate", "Aegis of Facets", "Bastion", "Undying" },
  { "Heavy Bonk", "Fracture Point", "Meteor Bonk", "Devastate", "Cataclysm" },
  { "Second Wind", "Iron Will", "Last Stand", "Warden Spirit", "Immovable" }
};
static const char *const skill_desc[3][5] = {
  { "+25 max HP",
    "+3 defense",
    "Prism Shield blocks far more",
    "+30 max HP & +2 defense",
    "CAPSTONE: once per life, revive at 50% HP" },
  { "+25% Bonk damage",
    "+12% crit chance",
    "+40% Bonk damage",
    "+30% Bonk damage & +6% crit",
    "CAPSTONE: +50% Bonk damage & +12% crit" },
  { "Heal 25% HP after every victory",
    "+2 defense",
    "Survive a fatal blow once per battle",
    "+3 regen & heal 15% after each win",
    "CAPSTONE: +25% max HP & +4 defense" }
};
#elif TREE_CLASS == 2 /* whisperer */
static const char *const branch_name[3] = { "Kinship", "Blessing", "Wild" };
static const char *const skill_name[3][5] = {
  { "Best Friends", "Loyal Companion", "Radiant Herd", "Herd Leader", "Celestial Herd" },
  { "Gentle Glow", "Warm Heart", "Meadow Soul", "Radiant Soul", "Unicorn's Gift" },
  { "Forager", "Fae Steps", "Old Tales", "Lucky Charm", "Storyteller" }
};
static const char *const skill_desc[3][5] = {
  { "Unicorns 30% stronger",
    "Summons last 2 extra turns",
    "Unicorns 50% stronger",
    "Summons last +3 turns",
    "CAPSTONE: +70% unicorn power" },
  { "Healing 30% stronger",
    "+20 max HP",
    "Regenerate 3 HP every battle turn",
    "+25% healing & +15 max HP",
    "CAPSTONE: once per life, your unicorn sacrifices itself to revive you at 50% HP" },
  { "+1 mineral from every node",
    "Fleeing always works, never ambushed",
    "+25% XP from battles",
    "+18% chance of a bonus rare gem when mining",
    "CAPSTONE: +40% XP from battles" }
};
#endif
