/* Generated by tools/gen_data.js from js/data.js -- do not edit. */
#include "tree.h"

const Branch tree[3][3] = {
  { /* mage */
    { 4, {
      { { { E_SPELLDMG, 15 }, { E_NONE, 0 } } }, /* Focused Light */
      { { { E_CRIT, 12 }, { E_NONE, 0 } } }, /* Prismatic Edge */
      { { { E_SPELLDMG, 25 }, { E_NONE, 0 } } }, /* Supernova Heart */
      { { { E_SPELLDMG, 20 }, { E_NONE, 0 } } }, /* Starfire */
      { { { E_SPELLDMG, 40 }, { E_CRIT, 12 } } }, /* Prismatic Nova */
    } },
    { 3, {
      { { { E_POLISH, 35 }, { E_NONE, 0 } } }, /* Steady Hands */
      { { { E_CHARGES, 1 }, { E_NONE, 0 } } }, /* Echo Casting */
      { { { E_CHARGESAVE, 25 }, { E_NONE, 0 } } }, /* Chain Light */
      { { { E_CHARGES, 1 }, { E_CHARGESAVE, 15 } } }, /* Mana Well */
      { { { E_REVIVE, 50 }, { E_NONE, 0 } } }, /* Second Dawn */
    } },
    { 7, {
      { { { E_MINEYIELD, 1 }, { E_NONE, 0 } } }, /* Gem Sense */
      { { { E_XPGAIN, 25 }, { E_NONE, 0 } } }, /* Scholar */
      { { { E_RARELUCK, 20 }, { E_NONE, 0 } } }, /* Rainbow Luck */
      { { { E_MINEYIELD, 1 }, { E_RARELUCK, 12 } } }, /* Gem Diviner */
      { { { E_XPGAIN, 40 }, { E_RARELUCK, 20 } } }, /* Midas Prism */
    } },
  },
  { /* knight */
    { 3, {
      { { { E_HPMAX, 25 }, { E_NONE, 0 } } }, /* Stonewall */
      { { { E_DEFFLAT, 3 }, { E_NONE, 0 } } }, /* Crystal Plate */
      { { { E_SHIELD, 50 }, { E_NONE, 0 } } }, /* Aegis of Facets */
      { { { E_HPMAX, 30 }, { E_DEFFLAT, 2 } } }, /* Bastion */
      { { { E_REVIVE, 50 }, { E_NONE, 0 } } }, /* Undying */
    } },
    { 7, {
      { { { E_BASICDMG, 25 }, { E_NONE, 0 } } }, /* Heavy Bonk */
      { { { E_CRIT, 12 }, { E_NONE, 0 } } }, /* Fracture Point */
      { { { E_BASICDMG, 40 }, { E_NONE, 0 } } }, /* Meteor Bonk */
      { { { E_BASICDMG, 30 }, { E_CRIT, 6 } } }, /* Devastate */
      { { { E_BASICDMG, 50 }, { E_CRIT, 12 } } }, /* Cataclysm */
    } },
    { 3, {
      { { { E_HEALONWIN, 25 }, { E_NONE, 0 } } }, /* Second Wind */
      { { { E_DEFFLAT, 2 }, { E_NONE, 0 } } }, /* Iron Will */
      { { { E_LASTSTAND, 1 }, { E_NONE, 0 } } }, /* Last Stand */
      { { { E_REGEN, 3 }, { E_HEALONWIN, 15 } } }, /* Warden Spirit */
      { { { E_HPMAX, 25 }, { E_DEFFLAT, 4 } } }, /* Immovable */
    } },
  },
  { /* whisperer */
    { 4, {
      { { { E_UNICORN, 30 }, { E_NONE, 0 } } }, /* Best Friends */
      { { { E_SUMMONTURNS, 2 }, { E_NONE, 0 } } }, /* Loyal Companion */
      { { { E_UNICORN, 50 }, { E_NONE, 0 } } }, /* Radiant Herd */
      { { { E_SUMMONTURNS, 3 }, { E_NONE, 0 } } }, /* Herd Leader */
      { { { E_UNICORN, 70 }, { E_NONE, 0 } } }, /* Celestial Herd */
    } },
    { 3, {
      { { { E_HEALPOWER, 30 }, { E_NONE, 0 } } }, /* Gentle Glow */
      { { { E_HPMAX, 20 }, { E_NONE, 0 } } }, /* Warm Heart */
      { { { E_REGEN, 3 }, { E_NONE, 0 } } }, /* Meadow Soul */
      { { { E_HEALPOWER, 25 }, { E_HPMAX, 15 } } }, /* Radiant Soul */
      { { { E_REVIVE, 50 }, { E_NONE, 0 } } }, /* Unicorn's Gift */
    } },
    { 7, {
      { { { E_MINEYIELD, 1 }, { E_NONE, 0 } } }, /* Forager */
      { { { E_FLEESURE, 1 }, { E_NONE, 0 } } }, /* Fae Steps */
      { { { E_XPGAIN, 25 }, { E_NONE, 0 } } }, /* Old Tales */
      { { { E_RARELUCK, 18 }, { E_NONE, 0 } } }, /* Lucky Charm */
      { { { E_XPGAIN, 40 }, { E_NONE, 0 } } }, /* Storyteller */
    } },
  },
};

const Eff class_perk[3][2] = {
  { { E_SPELLDMG, 35 }, { E_CHARGESAVE, 10 } }, /* mage */
  { { E_BASICDMG, 50 }, { E_SPELLDMG, -10 } }, /* knight */
  { { E_UNICORN, 35 }, { E_NONE, 0 } }, /* whisperer */
};
